### ISSUE TITLE
Client is Unable to Communicate with Child Components

### ISSUE THREAD

**Issue by m-orosa** [ScottyMcCotty/LettuCSE#10]
There is currently no communication functionality between the client and its child components.

For this issue to be closed, the client must be able to cause some change in the child components, such as turning an LED on or off, *and* confirm that the change has taken place.

**Comment by ScottyMcCotty** [comment]
There is now an Arduino with 2 LEDs attached. The Arduino listens for Serial commands and responds when the task has been complete, or sends an error if the task is incompletable.
`red` turns the red LED on for a pre-determined duration
`blue` turns the blue LED on for a pre-determined duration
`purple` turns the red and blue LEDs on for a pre-determined duration
Any other command sends an error message.
The pre-determined duration (1000 ms) is hard-coded into the Arduino but can be passed by the client in future versions
