### ISSUE TITLE
We lost points on the team agreement

### ISSUE THREAD

**Issue by ScottyMcCotty** [ScottyMcCotty/LettuCSE#3]
An entire .4 points

Tyler's comment:

- Contacting response time not listed
- Missing team's contact information
- Missing project name
- Missing team name/number

**Comment by Lumgineer** [comment]
Filled in 3 of the 4 bullet points. Rest of team needs to go in and fill out their own contact response time (I listed mine as under 24 hours to be safe but would probably respond much faster most of the time)

**Comment by MiraWelner** [comment]
Added project name (because I don't think that was added) and my response time (listed as under 12 hours)

**Comment by ScottyMcCotty** [comment]
I made a pull request to fix this issue, and I linked them together to see what happens
